name: Deploy to OVH FTP
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.cluster100.hosting.ovh.net
          username: demenam
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: ./
          server-dir: /louveciennes78350/
          exclude: |
            **/.git*
            **/.git*/**
